# Generated by Django 2.2 on 2019-06-07 21:27

import client.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(default='Unset', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channelId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('channelTitle', models.CharField(max_length=200)),
                ('channelStatus', models.CharField(choices=[('unset', 'UNSET'), ('trusted', 'TRUSTED'), ('untrusted', 'UNTRUSTED')], default='unset', max_length=10)),
                ('channelUrl', models.URLField(max_length=250)),
                ('channelViewCount', models.IntegerField(blank=True, null=True)),
                ('channelCommentCount', models.IntegerField(blank=True, null=True)),
                ('channelSubscriberCount', models.IntegerField(blank=True, null=True)),
                ('channelVideoCount', models.IntegerField(blank=True, null=True)),
                ('publishedAt', models.DateTimeField(null=True, verbose_name='publishedAt')),
                ('channelCategory', models.ForeignKey(default=client.models.Category, on_delete=django.db.models.deletion.CASCADE, to='client.Category')),
            ],
            options={
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('lastVisitAt', models.DateTimeField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=200, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=5, null=True)),
                ('os', models.CharField(blank=True, max_length=20, null=True)),
                ('os_version', models.CharField(blank=True, max_length=20, null=True)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True)),
                ('continent', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Viewers',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('channelTitle', models.CharField(max_length=200)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('lastModified', models.DateTimeField(blank=True, null=True)),
                ('thumbnailsLow', models.ImageField(blank=True, max_length=250, null=True, upload_to='')),
                ('thumbnailsHigh', models.ImageField(blank=True, max_length=250, null=True, upload_to='')),
                ('thumbnailsMedium', models.ImageField(blank=True, max_length=250, null=True, upload_to='')),
                ('url', models.URLField(max_length=250)),
                ('license', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('subtitles', models.CharField(blank=True, max_length=200, null=True)),
                ('artist', models.CharField(blank=True, max_length=200, null=True)),
                ('track', models.CharField(blank=True, max_length=200, null=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('resolution', models.CharField(blank=True, max_length=200, null=True)),
                ('ext', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('dislike_count', models.IntegerField(blank=True, default=0, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('downloaded', 'DOWNLOADED'), ('uploaded', 'UPLOADED'), ('skipped', 'SKIPPED')], default='pending', max_length=10)),
                ('video', models.URLField(max_length=300)),
                ('category', models.ForeignKey(default=client.models.Category, on_delete=django.db.models.deletion.CASCADE, to='client.Category')),
                ('channel', models.ForeignKey(default=client.models.Channel, on_delete=django.db.models.deletion.CASCADE, to='client.Channel')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(default=client.models.Category, on_delete=django.db.models.deletion.CASCADE, to='client.Category')),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('link', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('published', 'published'), ('unpublished', 'unpublished')], default='unpublished', max_length=12)),
                ('category', models.ForeignKey(default=client.models.Category, on_delete=django.db.models.deletion.CASCADE, to='client.Category')),
            ],
            options={
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostTag', models.TextField(blank=True)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(default=client.models.Video, on_delete=django.db.models.deletion.CASCADE, to='client.Video')),
            ],
        ),
    ]
