# Generated by Django 2.2.1 on 2019-06-24 15:41

import client.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_radiostation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweeter',
            fields=[
                ('tweeterName', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unset', 'UNSET'), ('trusted', 'TRUSTED'), ('untrusted', 'UNTRUSTED')], default='unset', max_length=10)),
                ('url', models.URLField(max_length=250)),
                ('followers_count', models.IntegerField(blank=True, null=True)),
                ('statuses_count', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.URLField(max_length=250)),
                ('category', models.ForeignKey(default=client.models.Category, on_delete=django.db.models.deletion.CASCADE, to='client.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweetId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tweet', models.TextField(blank=True, null=True)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('published', 'published'), ('unpublished', 'unpublished')], default='unpublished', max_length=12)),
                ('tweeter', models.ForeignKey(default=client.models.Tweeter, on_delete=django.db.models.deletion.CASCADE, to='client.Tweeter')),
            ],
        ),
    ]
