# Generated by Django 2.2.1 on 2019-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_tweet_tweeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnailsHigh',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnailsLow',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnailsMedium',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
