# Generated by Django 2.2.1 on 2019-07-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20190701_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
