# Generated by Django 2.2.1 on 2019-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_facebookpost_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='status',
            field=models.CharField(choices=[('blocked', 'BLOCKED'), ('unset', 'UNSET')], default='unset', max_length=12),
        ),
    ]
